In [1]:
import pandas as pd

df1 = pd.read_csv('C:/Github/EEG-Mouse/data/train.csv', header=None)
df2 = pd.read_csv('C:/Github/EEG-Mouse/outputs/1d_model/final/concatenated_train_final_data_epoch_final.csv', header=None)

# Check exact equality (values and shape)
are_equal = df1.equals(df2)

print("Files are equal:" if are_equal else "Files are different.")

Files are different.

In [2]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279
0,30.088278,58.298913,75.966152,71.572342,41.492319,3.738996,-10.255864,22.190196,78.897725,109.698217,...,111.674031,128.364208,104.117430,55.400625,0.786699,-42.640312,-62.099563,-65.570511,-77.820289,-106.489794
1,-121.407340,-100.747982,-65.330241,-38.441355,-35.750788,-56.006537,-82.028244,-97.005947,-105.138312,-123.529299,...,-31.278507,-42.605480,-44.566211,-45.260265,-53.360069,-51.173040,-22.597792,14.711455,33.111333,18.305954
2,-28.355988,-31.862925,-16.072848,6.351046,28.004965,40.304392,26.985305,-14.892353,-57.970621,-66.476236,...,-16.939070,-27.460534,-55.878847,-73.674563,-61.688021,-43.413644,-36.207856,-26.195530,-6.150226,17.525786
3,-85.012211,-76.476292,-79.968394,-101.516080,-124.068800,-124.180187,-98.184534,-63.555797,-36.025803,-21.056813,...,-154.284862,-186.018462,-193.486397,-179.723877,-164.487542,-157.327509,-145.460304,-117.543171,-82.341686,-54.206591
4,-33.806979,-48.535948,-79.573954,-110.908244,-128.587110,-133.524734,-128.653265,-113.150259,-95.529259,-88.067007,...,6.036766,2.180292,-0.774978,9.157403,29.131027,52.762981,68.311172,68.258510,59.904841,54.874402

In [3]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279
0,30.088278,58.298912,75.96615,71.572340,41.492317,3.738996,-10.255864,22.190195,78.897730,109.698220,...,89.846200,67.239586,38.118500,44.178986,64.683334,-36.080498,-33.053947,-6.007597,20.672697,20.672691
1,-121.407340,-100.747986,-65.33024,-38.441357,-35.750790,-56.006540,-82.028244,-97.005940,-105.138310,-123.529300,...,-87.540330,-89.984760,-51.250603,1.481621,-14.136948,-89.726250,48.201100,81.890854,85.669914,85.669914
2,-28.355988,-31.862925,-16.07285,6.351046,28.004965,40.304394,26.985306,-14.892353,-57.970620,-66.476234,...,69.319275,55.746900,48.740400,49.558940,59.131720,-14.534351,-59.444645,-58.413500,-81.349570,-81.349580
3,-85.012215,-76.476295,-79.96839,-101.516080,-124.068800,-124.180190,-98.184530,-63.555798,-36.025803,-21.056812,...,-40.318245,-16.208640,30.891230,57.603306,77.410930,-35.329937,88.900276,89.754654,89.848830,89.848830
4,-33.806980,-48.535950,-79.57395,-110.908240,-128.587110,-133.524730,-128.653260,-113.150260,-95.529260,-88.067010,...,-0.872234,23.065622,45.510490,48.781906,75.011580,82.506040,88.822310,89.957240,89.981514,89.981514